### PR TITLE
Reload cards on icon click

### PR DESCRIPTION
**Pull request by gustavi**
By default, when a card is added/removed/renamed the change is not view by the plugin.

This code just add a Listener that reload the list on each click.

### CODE REVIEW

**Comment by ret394** [comment]
I'll test it later.

thanks

**Comment by gustavi** [comment]
@necropola ?

**Comment by necropola** [comment]
https://github.com/rain-fighters/AudioPick/issues/47

**Comment by necropola** [comment]
I closed the PR, because it is no longer relevant. The version that someone posted in the above mentioned issue is a complete rewrite of the extension which is supposed to work with the soon be mandatory Manifest V3.

My original approach does not work properly for quite some time already and will completely cease to work, as soon as Manifest V3 is enforced. Extensions with Manifest V2 cannot be updated for quite some time already.

**Pull request closed without merging**
